Created pages
pedrofcantunes/E-shop-vanilla-Curso pull request #3
Opened 2022-05-31 03:35 UTC by pedrofcantunes

Created main and checkout page

https://user-images.githubusercontent.com/99771592/171087655-aae270de-7539-44c5-bc67-5aef1aa1c3fa.mp4

2022-05-31 22:59 UTC, yoannes requested changes

2022-05-31 22:59 UTC, yoannes commented on src/css/css.css
>  }
É importante ter a ultima linha no arquivo, pode trazer erros quando colocar o site no ar

https://stackoverflow.com/a/44704969/4066787

2022-05-31 22:59 UTC, yoannes commented on src/js/controllers.js
>  }
É importante ter a ultima linha no arquivo, pode trazer erros quando colocar o site no ar

https://stackoverflow.com/a/44704969/4066787

2022-06-01 00:34 UTC, pedrofcantunes commented on src/css/css.css
>  }
Opa feito, valeu yoyo

2022-06-01 00:34 UTC, pedrofcantunes commented on src/js/controllers.js
>  }
Feito, valeu yoyo

2022-06-01 13:25 UTC, pedrofcantunes commented
Faço o Merge e mando novamente o pull request?

2022-06-02 13:25 UTC, merged